name: Deploy Workflow
on:
  workflow_dispatch:

env:
  SLACK_USERNAME: GitHub
  SLACK_ICON_EMOJI: ":github:"
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  set_matrix:
    name: Set Repository Matrix
    runs-on: ubuntu-latest
    steps:
      - name: SetRepositoryMatrix
        id: set_repository_matrix
        env: 
          GH_TOKEN: ${{ github.token }}
        run: |
          repositories=$(gh repo list ${{ github.repository_owner }} --json name --limit 999 | jq '[.[].name]')
          echo "targets=$(echo $repositories | jq -c .)" >> $GITHUB_OUTPUT
          echo $repositories
  
    outputs:
      targets: ${{ steps.set_repository_matrix.outputs.targets }}

  copy-workflow:
    name: Copy Workflow
    runs-on: ubuntu-latest
    needs: 
      - set_matrix
    strategy:
      matrix:
        targets: ${{ fromJson(needs.set_matrix.outputs.targets) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Echo Matrix
        run: echo ${{ matrix.targets }}

      # 他リポジトリに対してディレクトリをコピーする
      - name: Copy Workflow files
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        if: ${{ matrix.targets }} != ${{ github.event.repository.name }}
        env:
          API_TOKEN_GITHUB: ${{ steps.generate_token.outputs.token }}
        with:
          source_file: ".github"
          destination_repo: "${{ github.repository_owner }}/${{ matrix.targets }}"
          destination_folder: "./"
          destination_branch: "main"
          destination_branch_create: "feature/update-git-workflow"
          user_email: "github-actions[bot]@users.noreply.github.com"
          user_name: "github-actions[bot]"
          commit_message: "Gitワークフロー更新(自動コミット)"

      # 他リポジトリに対してPRを投げる
      - name: Create Pull Request to another-repo
        if: ${{ matrix.targets }} != ${{ github.event.repository.name }}
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh pr create \
            --title "Update GitWorkflow (Auto) " \
            --body "Gitワークフロー更新 from: ${{ github.event.repository.html_url }}" \
            --repo ${{ github.repository_owner }}/${{ matrix.targets }} \
            --base main \
            --head feature/update-git-workflow \
            --reviewer "${{ github.repository.head_commit.committer.username || github.triggering_actor }}"
 