name: Deploy Workflow
on:
  workflow_dispatch:

env:
  SLACK_USERNAME: GitHub
  SLACK_ICON_EMOJI: ":github:"
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  generate_token:
    name: Generate Access Token
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Copy Workflow files
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ steps.generate_token.outputs.token }}
        with:
          source_file: ".github"
          destination_repo: "G2-MORITA/g2-morita-test-1"
          destination_folder: "./"
          destination_branch: "main"
          destination_branch_create: "feature/update-git-workflow"
          user_email: "github-actions[bot]@users.noreply.github.com"
          user_name: "github-actions[bot]"
          commit_message: "Gitワークフロー更新(自動コミット)"

      - name: Create Pull Request to another-repo
        run: |
          gh pr create \
            --title "Update GitWorkflow (Auto) " \
            --body "Gitワークフロー更新 from: ${{ github.event.repository.html_url }}" \
            --repo G2-MORITA/g2-morita-test-1 \
            --base main \
            --head feature/update-git-workflow \
            --reviewer "${{ github.repository.head_commit.committer.username || github.triggering_actor }}"
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}