name: Pull Request Notification
on:
  pull_request:
    types: [opened, reopened]

env:
  SLACK_USERNAME: GitHub
  SLACK_ICON_EMOJI: ":github:"
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    name: Pull Request Notification Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm install
    
      # PRの内容を公開
      - name: PullRequest Open
        id: pr-info
        run: |
          echo The PR was opened
          echo "REPOSITORY_NAME=${{ github.event.repository.full_name }}" >> $GITHUB_OUTPUT
          echo "PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_OUTPUT

      # 作ったアクションの実行 ここから 
      - name: Create Message 
        uses: ./
        id: create-message 
        with: 
          TARGET_REPOSITORY_NAME: ${{ steps.pr-info.outputs.REPOSITORY_NAME }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}

      # Slackへの通知
      - name: Slack Notification
        if: success()  
        env:
          TEXT: "${{ steps.create-message.outputs.slack_channel }}"
          SLACK_CHANNEL: "${{ steps.create-message.outputs.slack_channel }}"
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"${TEXT}\", \"channel\":\"${SLACK_CHANNEL}\", \"username\":\"${SLACK_USERNAME}\", \"icon_emoji\":\"${SLACK_ICON_EMOJI}\"}" \
            ${SLACK_WEBHOOK}
