name: Pull Request Notification
on:
  pull_request:
    types: [opened, reopened]

env:
  SLACK_USERNAME: GitHub
  SLACK_ICON_EMOJI: ":github:"
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    name: Pull Request Notification Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm install
    
      # PRの内容を公開
      - name: Dump pull_request values
        run: | 
          echo '${{ toJSON(github.event.pull_request) }}'

      - name: Dump Repository values
        run: | 
          echo '${{ toJSON(github.event.repository) }}'

      - name: Dump Github values
        run: | 
          echo '${{ toJSON(github) }}'

      # 作ったアクションの実行 ここから 
      - name: Create Message 
        uses: ./
        id: create-message 
        with: 
          TARGET_REPOSITORY_NAME: ${{ github.event.repository.full_name }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}

      - name: Create slack-request-env.json file
        run: |
          cat -te << EOF > slack-request-env.json
          {
            "text": "",
            "channel": "${{ steps.create-message.outputs.slack_channel }}",
            "username": "$SLACK_USERNAME",
            "icon_emoji": "$SLACK_ICON_EMOJI",
            "attachments":
              [
                  {
                    "title": "#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}",
                    "title_link": "${{ github.event.pull_request.html_url }}",
                    "color": "good",
                    "text": "${{ github.event.pull_request.body }}",
                    "fields":
                    [
                        {
                            "title":"User",
                            "value": "${{ github.event.pull_request.user.name }}",
                            "short":true,
                        }
                    ]
                  }
              ]
          }
          EOF
          cat slack-request-env.json

      # Slackへの通知
      - name: Slack Notification
        if: success()  
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data @slack-request-env.json \
            ${SLACK_WEBHOOK}
